---
- name: Expand Physical Volumes on all the nodes
  pv: state={{state}}
      disks={{item.disks}}
      setphysicalvolumesize={{item.setphysicalvolumesize}}
  with_items:
  - "{{ pvextend_list}}"

# tasks file for pvextend
